name: Continuous Deployment

on:
  push:
    branches: [main]

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GH_OWNER_TOKEN }}
          release-type: simple
